# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:8082/api/joda-time/select
Content-Type: application/json

{
  "query": "select * from joda_time"
}

###

POST http://localhost:8082/api/joda-time/select
Content-Type: application/json

{
  "query": "select start, to_char_with_tz(start, 'YYYY-MM-DD HH24:MI:SS', 'Europe/Moscow') from joda_time order by start limit 3"
}

###

POST http://localhost:8082/api/joda-time/select-with-params
Content-Type: application/json

{
  "query": "select start, to_char_with_tz(start, 'YYYY-MM-DD HH24:MI:SS', 'Europe/Moscow') from joda_time where start = minus_tz_offset(@date, 'Europe/Moscow') order by start limit 3",
  "params": [
    {
      "name": "date",
      "value": "2018-08-24",
      "type": "DATE"
    }
  ]
}

###

POST http://localhost:8082/api/joda-time/select-with-params
Content-Type: application/json

{
  "query": "select start, to_char_with_tz(start, 'YYYY-MM-DD HH24:MI:SS', 'Europe/Samara') from joda_time where start = minus_tz_offset(@date, 'Europe/Samara') order by start limit 3",
  "params": [
    {
      "name": "date",
      "value": "2018-08-24",
      "type": "DATE"
    }
  ]
}

###

POST http://localhost:8082/api/joda-time/select-with-params
Content-Type: application/json

{
  "query": "select start, to_char_with_tz(start, 'HH24:MI:SS', 'Europe/Samara') from joda_time where start = minus_tz_offset(@date, 'Europe/Samara') order by start limit 3",
  "params": [
    {
      "name": "date",
      "value": "2018-08-24",
      "type": "DATE"
    }
  ]
}

###