package net.projecteuler.problem02;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

/**
 * Solution:
 * By starting with 1 and 1, every third number
 * of Fibonacci sequence will be even
 */

public class Problem02Solution02 {
    public static void main(String[] args) {
        System.out.println(Solution02.solve());
    }
}

class Solution02 {
    static final int BORDER = 4_000_000;

    static long solve() {
        long sum = 0;
        int fib1 = 1;
        int fib2 = 1;
        int fib3 = fib1 + fib2;
        while (fib3 <= BORDER) {
            sum += fib3;
            fib1 = fib2 + fib3;
            fib2 = fib1 + fib3;
            fib3 = fib1 + fib2;
        }
        return sum;
    }
}