package net.projecteuler.problem02;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

/**
 * Solution:
 * check every calculated Fibonacci number on even
 */

//todo check solution via unit-tests
public class Problem02Solution01 {
    public static void main(String[] args) {
        System.out.println(Solution01.solve());
    }
}

class Solution01 {
    static final int BORDER = 4_000_000;

    static long solve() {
        int f1 = 1;
        int f2 = 1;
        int fnext = f1 + f2;
        long sum = 0;
        while (fnext <= BORDER) {
            if (fnext % 2 == 0) {
                sum += fnext;
            }
            f1 = f2;
            f2 = fnext;
            fnext = f1 + f2;
        }
        return sum;
    }
}